const skillArray = [
    "JavaScript",
    "Python",
    "Java",
    "C++",
    "HTML",
    "CSS",
    "React",
    "Angular",
    "Node.js",
    "SQL",
    "MongoDB",
    "Git",
    "AWS",
    "Docker",
    "PHP",
    "Ruby",
    "Swift",
    "Rust",
    "Scala",
    "TypeScript",
    "Kotlin",
    "C#",
    "Unity",
    "TensorFlow",
    "PyTorch",
    "Data Science",
    "Machine Learning",
    "Artificial Intelligence",
    "Cybersecurity",
    "Network Security",
    "Web Development",
    "Mobile App Development",
    "Blockchain",
    "Big Data",
    "Cloud Computing",
    "UI/UX Design",
    "Game Development",
    "DevOps",
    "Natural Language Processing",
    "Computer Vision",
    "Operating Systems",
    "Database Management",
    "Software Engineering",
    "Agile Methodology",
    "Computer Networks",
    "Internet of Things (IoT)",
    "Virtual Reality (VR)",
    "Augmented Reality (AR)",
    "Quantum Computing",
    "Microservices",
    "Frontend Development",
    "Backend Development",
    "API Development",
    "Testing and Quality Assurance",
    "Data Structures and Algorithms",
    "Object-Oriented Programming (OOP)",
    "Responsive Web Design",
    "Serverless Architecture",
    "Parallel Computing",
    "Flutter",
    "Vue.js",
    "Express.js",
    "Spring Boot",
    "Ruby on Rails",
    "ASP.NET",
    "TensorFlow.js",
    "Natural Language Toolkit (NLTK)",
    "OpenCV",
    "Hadoop",
    "Spark",
    "Tableau",
    "Adobe XD",
    "Sketch",
    "Figma",
    "InVision",
    "User Research",
    "Penetration Testing",
    "Firewalls",
    "Encryption",
    "SIEM",
    "Unreal Engine",
    "Game Design",
    "Asset Pipeline",
    "Jenkins",
    "Ansible",
    "CI/CD",
    "MySQL",
    "Oracle",
    "Database Design",
    "Deep Learning",
    "SpaCy",
    "BERT",
    "Text Classification",
    "Test Planning",
    "Test Automation",
    "Selenium",
    "Bug Tracking",
    "Power BI",
    "D3.js",
    "Data Storytelling",
    "Interactive Dashboards",
    "AWS Lambda",
    "Azure Functions",
    "Google Cloud Functions",
    "Serverless Framework",
    "CUDA",
    "OpenMP",
    "MPI",
    "Parallel Algorithms",
    "Distributed Systems",
    "3D Modeling",
    "VR Interaction",
    "ARKit",
    "ARCore",
    "Markerless Tracking",
    "Quantum Gates",
    "Quantum Algorithms",
    "Quantum Simulators",
    "Qiskit",
    "Quantum Cryptography",
    "RESTful APIs",
    "Message Brokers",
    "Service Discovery"
  ];
  
  export default skillArray;
  